### ISSUE TITLE
Editing bovada

### ISSUE THREAD

**Issue by ethan4540** [anandijain/sips#6]
Edit bovada so that we can specify what we are scraping using a specific game id, it should output a list of the stats from bovada for that individual game.

**Comment by anandijain** [comment]
Please specific specific code examples for functionality that you would like to see in the package.

**Comment by ethan4540** [comment]
import scraper.bov
lines = bov.get(game id) 
lines = a list of the current lines for that specific game

**Comment by anandijain** [comment]
use the `backticks` when writing code
